### PR TITLE
typo in readme fixed

### PR DESCRIPTION
**Pull request by SiebeCooreman**
excerises is spelled exercises! :)
also this is the first time I'm doing a pull request. The reason I'm doing this is to actually see if I do it correctly!
My apologies if I screwed something up.

### CODE REVIEW

**Comment by SiebeCooreman** [comment]
there are seemingly typos in the .ddl file. I also added .DS_Store to the .gitignore (for mac users that fork this repo). Even though I did this by accident, it actually also is a useful pull request.

**Comment by johanpck** [comment]
Thanks Siebe. But it seems you've closed the PR, so I can't merge...

**Comment by SiebeCooreman** [comment]
Aha! I didn't know that closing a PR actually blocks you from merging in whatever commits it contained.
I did this so I could continue working on the project without pushing my personal changes to this PR. I'll look into later today.

**Comment by SiebeCooreman** [comment]
can you merge now that it is reopened? @johanpck

**Comment by johanpck** [comment]
Thanks Siebe, merged in!

**Pull request merged**
